services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Mah-Jong-Points-Calculator
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: ${DB_HOST}
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql/
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_USER_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

volumes:
  db-data: